services:
  mkdocs-serving:
    image: python:3.11-slim
    volumes:
      - ./:/app/
    working_dir: /app
    ports:
      - "49161:8000"
    command: >
      bash -c "
        apt update &&
        apt install git unzip libcairo2 libcairo2-dev libpango-1.0-0 libpangocairo-1.0-0 libjpeg-dev zlib1g-dev -y &&
        pip install uv &&
        uv pip install -r requirements.txt --python /usr/local/bin/python3 &&
        git config --global --add safe.directory /app &&
        mkdir -p /app/.cache/plugin/social/fonts && 
        cp /app/fonts/Roboto.zip /app/.cache/plugin/social/fonts/Roboto.zip &&
        unzip -o /app/.cache/plugin/social/fonts/Roboto.zip -d /app/.cache/plugin/social/fonts/Roboto  &&
        mkdocs serve -a 0.0.0.0:8000"
