# Copyright (c) 2016-2023 Martin Donath <martin.donath@squidfunk.com>
# Copyright (c) 2023-2024 Hermann Agossou <agossouhermann7@gmail.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: What I learned today (@hermann-web)
site_url: https://hermann-web.github.io/blog/
site_author: Hermann Agossou
site_description: >-
  Meet Hermann, a pro at full-stack web development and data science, acing website building, backend systems, ML & DL (NLP and 3D vision included). These tutorials? They're my personal cheat sheets—where I stash those markdown, GitHub nuggets: syntax, functions, handy tools—stuff I use all the time. Now, I'm turning some into blog posts. Join me in simplifying our learning journeys, building a shared resource that evolves as we grow.

# Repository
repo_name: hermann-web/blog
repo_url: https://github.com/hermann-web/blog/

docs_dir: docs/

lang: en

# Copyright
copyright: Copyright © 2023-2024 Hermann Agossou

google_analytics: ['BD4YrWd0pEc2SUULdRPLKgv5QCfeDluhXPt37gL9nNs', 'hermann-web.github.io']

# Configuration
theme:
  name: dracula
  language: en
  lang: en
  custom_dir: material/overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/logo-blog-hermann-agossou-ot0-500x500.png
  icon:
    logo: logo
  logo: assets/logo-blog-hermann-agossou-ot20-500x500.png

# Plugins
plugins:
  - blog
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  # https://timvink.github.io/mkdocs-git-revision-date-localized-plugin/options/
  - git-revision-date-localized:
      type: timeago
      timezone: Europe/Amsterdam
      locale: en
      fallback_to_build_date: false
      enable_creation_date: true

# # Hooks
# hooks:
#   - material/overrides/hooks/shortcodes.py
#   - material/overrides/hooks/translations.py

  # - social


# Additional configuration
extra:
  annotate:
    json: [.s2]
  analytics:
    provider: google
    property: BD4YrWd0pEc2SUULdRPLKgv5QCfeDluhXPt37gL9nNs
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hermann-web
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/agossou-hermann
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/hermann-web/hermann-web.github.io/
    - icon: fontawesome/brands/python
      link: https://pypi.org/user/Hermann-web/
    - icon: fontawesome/brands/researchgate
      link: https://researchgate.net/profile/Hermann-Agosou
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/AgossouHermann

  version:
    provider: mike
  analytics:
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback!

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: hermann-web
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  # - pymdownx.snippets:
  #     auto_append:
  #       - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

  ## math parsing extensions
  - pymdownx.arithmatex:
      generic: true

  - markdown.extensions.meta:
  - markdown.extensions.attr_list:
  - markdown.extensions.footnotes:
      PLACE_MARKER: "<!-- Footnotes -->"

# Page tree
nav:
  - Home: index.md
  - Projects:
    - Overview: projects/index.md
    - Bots Detection in Auction: projects/bot_detection_in_auction.md
    - Search Engine in french: projects/search-engine-for-domain-specific-french-users.md
    - Flask based File Hosting (web app & api & python module & cli app): projects/file-hosting-app.md
    - Streamlit App for Formula OCR using pix2tex: projects/image-to-latex-formula.md
    - Introducing Two New Packages for Streamlining File Conversions in Python: projects/introducing-two-new-packages-for-streamlining-file-conversions-in-python.md
    - Introducing the `lissajou` Package for Image and 2D/3D Plot Animation: projects/introducing-lissajou-for-animated-plots.md
  - The JavaScript Edge:
    - Home: projects/js-course/index.md
    - JavaScript Syntax Fundamentals: projects/js-course/javascript-fundamentals-simplified.md
    - Intermediate JavaScript Concepts: projects/js-course/javascript-concepts-intermediate.md
  - Blog:
    - blog/index.md


extra_javascript:
  # formula handling with katex
  - javascripts/katex.js 
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js  
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
  # formula handling with mathjax
  #  - javascripts/mathjax.js
  #  - https://polyfill.io/v3/polyfill.min.js?features=es6
  #  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
  - stylesheets/float-img.css
  - stylesheets/custom-admonition.css
